name: customerlabs_attribution
version: 1.0.0
config-version: 2

profile: customerlabs_profile # must match your dbt Cloud connection

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  customerlab:
    staging:
      +schema: customer_lab
      +materialized: view
    intermediate:
      +schema: customer_lab
      +materialized: table
    marts:
      +schema: customer_lab
      +materialized: table
