name: "customerlab"
version: "1.0.0"
config-version: 2

profile: "customerlab"

models:
  customerlab:
    # remove +schema override, let dbt Cloud handle dataset
    staging:
      +materialized: view   # lightweight views for raw GA4 events

    intermediate:
      +materialized: table  # stable tables for session logic

    marts:
      +materialized: table  # fact/mart tables for dashboards
